### PR TITLE
Add new datapoint permission definition to allow users to vew all dat…

### PR DESCRIPTION
**Pull request by benji811124**
…a points.

RAD-899
RAD-971

### CODE REVIEW

**Review by terrypacker — CHANGES_REQUESTED** [review]
@benji811124 when adding an i18 translation key `users.permissions.view.dataPoint ` you need to also add the i18n.properties file in the resources directory.

image

**Comment by benji811124** [comment]
I'll fix that.

**Review by terrypacker — CHANGES_REQUESTED** [review]
@benji811124 I've found that there are additional changes that need to be made for this, I tried to create a watchlist as a user that can view any data point and was not able to.  This is because there is a check in the validation logic that uses this:

```
if (vo.getType() == WatchListType.STATIC) {
            // Validate Points, we cannot trust the permissions from the passed in points from vo, we must look them up from the DB
            List<IDataPoint> newSummaries = vo.getPointList().stream().map(s -> {
                try {
                    return dataPointService.getSummary(s.getXid());
                } catch (PermissionException e) {
                    response.addContextualMessage("points", "watchlist.validate.pointNoReadPermission", s.getXid());
                } catch (NotFoundException e) {
                    response.addContextualMessage("points", "watchList.validate.pointNotFound", s.getXid());
                }
                return null;
            }).filter(Objects::nonNull).collect(Collectors.toList());

            vo.setPointList(newSummaries);
        }
```

What I found is that in many places in the codebase we are using `PermissionService.hasPermission()` and `PermissionService.ensurePermission()` to check to see if a User has read access to a data point which won't hit the changes you made.  The remaining part left to fix will be to check for references to `DataPointVO.getReadPermission()` and either use the `DataPointService.hasReadPermission()` or inject the new `DataPointPermissionDefinition` and check that as well.  I would suggest using the `hasReadPermission` method as the preferred solution.

**Comment by terrypacker** [comment]
@benji811124 also this didn't make it into 4.2.0 so please move your release note into a new section for the core:

```
*Version 4.2.1*
* Add new datapoint permission definition to allow users to vew all data points.
```

**Comment by benji811124** [comment]
@terrypacker, I think this still need to be merged

**Pull request merged**
